# ==============================================================================
# CROSS: METHODS VS METHODS
# ==============================================================================
# Cross-method concordance: for a fixed reference genome, compare TPM across
# different alignment/quantification methods. This is the default mode.

concordance_mode = "cross_method"

master_reference = "GPE001970_genome"

methods = "M1_HISAT2_RefGuided M2_HISAT2_DeNovo M3_STAR_Align M4_Salmon_Saf M5_RSEM_Bowtie2"

gene_groups = "SmelDMPs_v5_with_18s_and_HAP2,Selected_SmelGRF-GIF_with_two_GIF"
