#!/usr/bin/env Rscript

# ===============================================
# PROCESSING ENGINE FOR ALL ANALYSIS MODULES
# ===============================================
# Generic processing loop to avoid repetition across scripts
#
# Prerequisite: 0_shared_config.R and 1_utility_functions.R must be sourced first.
if (!exists("CURRENT_METHOD")) {
  stop("2_processing_engine.R requires 0_shared_config.R to be sourced first (CURRENT_METHOD not found)")
}

# ===============================================
# GENERIC PROCESSING FUNCTION
# ===============================================

# Big O: O(G × L × C × T × B × N) where G=gene_groups, L=processing_levels,
# C=count_types, T=gene_types, B=label_types, N=norm_schemes.
# Inner loop body is O(genes × samples) for normalization/labeling.
# .log2_cache reduces redundant log2 computation from O(N × genes × samples) to O(genes × samples).
# .rds caching in read_count_matrix reduces repeated file I/O from O(parse_time) to O(deserialize_time).
process_all_combinations <- function(
  config,
  output_base_dir,
  processing_callback,
  min_rows = 2,
  extra_options = NULL,
  matrices_dir = NULL  # Auto-detect based on method if NULL
) {
  counters <- list(total = 0, successful = 0, skipped = 0)
  
  # Auto-detect matrices directory based on current method
  if (is.null(matrices_dir)) {
    matrices_dir <- get_matrices_dir(CURRENT_METHOD)
  }
  
  # Get method-appropriate count types (filter COUNT_TYPES to valid ones for method)
  method_type <- get_method_type(CURRENT_METHOD)
  valid_count_types <- get_count_types(CURRENT_METHOD)
  
  # Map user-configured count types to method-equivalent types
  # When a user requests a count type that doesn't exist for a method,
  # map it to the closest available alternative.
  count_type_mapping <- list(
    "stringtie" = list(
      # No fallback for expected_count: coverage is per-base depth, NOT raw fragment counts.
      # Mapping expected_count → coverage would produce misleading results (e.g., invalid CPM/DESeq2).
      "tpm" = "tpm",
      "fpkm" = "fpkm",
      "coverage" = "coverage"
    ),
    "salmon" = list(
      "expected_count" = "NumReads",
      "tpm" = "tpm",
      "NumReads" = "NumReads"
    ),
    "rsem" = list(
      "expected_count" = "expected_count",
      "tpm" = "tpm"
      # NOTE: RSEM also produces FPKM (column 7 of .genes.results), but tximport
      # only outputs counts + TPM. No fpkm matrices are generated by the pipeline.
    ),
    "star" = list(
      "expected_count" = "NumReads",
      "tpm" = "tpm",
      "NumReads" = "NumReads"
    )
  )
  
  # Get mapping for current method (or use identity mapping)
  method_mapping <- count_type_mapping[[method_type]]
  if (is.null(method_mapping)) {
    method_mapping <- setNames(as.list(valid_count_types), valid_count_types)
  }
  
  # Map configured count types to method-appropriate ones
  active_count_types <- unique(unlist(lapply(COUNT_TYPES, function(ct) {
    if (!is.null(method_mapping[[ct]])) {
      method_mapping[[ct]]
    } else if (ct %in% valid_count_types) {
      ct
    } else {
      NULL
    }
  })))
  
  dropped_count_types <- COUNT_TYPES[!COUNT_TYPES %in% names(method_mapping) & !COUNT_TYPES %in% valid_count_types]
  if (length(dropped_count_types) > 0) {
    cat("  Note: count types not available for", CURRENT_METHOD, "(", method_type, "):",
        paste(dropped_count_types, collapse = ", "), "\n")
  }

  if (length(active_count_types) == 0) {
    cat("  Warning: No valid count types for method", CURRENT_METHOD,
        "- configured:", paste(COUNT_TYPES, collapse = ","), "\n")
    return(counters)
  }
  
  # For StringTie, processing_level is not used in path, so use a placeholder
  active_processing_levels <- if (method_type == "stringtie") c("gene_level") else PROCESSING_LEVELS
  
  # Avoid nesting an inner <gene_group>_in_<dataset> folder when the run has
  # only one gene_group — the parent path already identifies it and the inner
  # folder duplicates the gene-group token (and was inconsistently produced
  # across analyses, e.g., I_Basic_Heatmap vs II_Heatmap_with_CV).
  .single_gene_group <- length(config$gene_groups) == 1L

  for (gene_group in config$gene_groups) {
    # Get combined output folder name (GeneGroup_in_Dataset)
    output_folder_name <- get_output_folder_name(gene_group, CURRENT_DATASET)
    cat("Processing gene group:", gene_group, "\n")
    if (nzchar(CURRENT_DATASET)) {
      cat("  Dataset:", CURRENT_DATASET, "-> Output folder:", output_folder_name, "\n")
    }

    gene_group_output_dir <- if (.single_gene_group) {
      output_base_dir
    } else {
      file.path(output_base_dir, output_folder_name)
    }
    ensure_output_dir(gene_group_output_dir, clean = FALSE)
    
    for (processing_level in active_processing_levels) {
      for (count_type in active_count_types) {
        # Hoist norm scheme computation outside gene_type/label_type loops —
        # schemes depend only on count_type, not on gene_type or label_type.
        # Eliminates O(|GENE_TYPES| × |LABEL_TYPES|) redundant get_norm_schemes() calls.
        valid_schemes <- get_norm_schemes(count_type)
        active_norm_schemes <- NORM_SCHEMES[NORM_SCHEMES %in% valid_schemes]
        dropped_schemes <- NORM_SCHEMES[!NORM_SCHEMES %in% valid_schemes]
        if (length(dropped_schemes) > 0) {
          cat("    Note: skipping invalid norm schemes for", count_type, ":",
              paste(dropped_schemes, collapse = ", "), "\n")
        }
        for (gene_type in GENE_TYPES) {
          for (label_type in LABEL_TYPES) {

            input_file <- build_input_path(gene_group, processing_level, count_type,
                                           gene_type, matrices_dir, config$master_reference,
                                           CURRENT_METHOD, label_type)

            validation <- validate_and_read_matrix(input_file, min_rows)

            if (!validation$success) {
              cat("  Skipping (", validation$reason, "):", processing_level, "|",
                  basename(input_file), "\n", sep = "")
              next
            }

            cat("  Processing:", processing_level, "|", count_type, "|", gene_type, "|",
                label_type, "- Found", validation$n_genes, "genes\n")
            # Pre-apply labels to raw data ONCE (independent of norm_scheme)
            # Normalization only changes values, not row/column structure,
            # so we label once and normalize the labeled data directly.
            raw_labeled <- apply_labels(validation$data, gene_group, gene_type, label_type)
            # Pre-compute log2 once on labeled data for all norm schemes that need it
            .log2_cache <- NULL
            needs_log2 <- any(active_norm_schemes %in% c("count_type_normalized", "zscore", "zscore_row", "zscore_scaled_to_ten"))
            if (needs_log2) {
              .log2_cache <- preprocess_for_count_type_normalized(raw_labeled, count_type)
            }
            for (norm_scheme in active_norm_schemes) {
              normalized_labeled <- apply_normalization(raw_labeled, norm_scheme, count_type, .log2_cache)

              if (is.null(normalized_labeled)) {
                cat("    Failed normalization:", norm_scheme, "\n")
                next
              }
              
              callback_result <- tryCatch(
                processing_callback(
                  gene_group = gene_group,
                  gene_group_output_dir = gene_group_output_dir,
                  processing_level = processing_level,
                  count_type = count_type,
                  gene_type = gene_type,
                  label_type = label_type,
                  norm_scheme = norm_scheme,
                  raw_data_matrix = raw_labeled,
                  normalized_data = normalized_labeled,
                  overwrite = config$overwrite_existing,
                  extra_options = extra_options
                ),
                error = function(e) {
                  cat("    [ERROR] Callback failed:", e$message, "\n")
                  list(total = 1L, successful = 0L, skipped = 0L)
                }
              )

              if (is.null(callback_result) ||
                  !all(c("total", "successful", "skipped") %in% names(callback_result))) {
                counters$total <- counters$total + 1L
                counters$skipped <- counters$skipped + 1L
              } else {
                counters$total <- counters$total + callback_result$total
                counters$successful <- counters$successful + callback_result$successful
                counters$skipped <- counters$skipped + callback_result$skipped
              }
            }
          }
        }
      }
    }
  }
  
  return(counters)
}

# ===============================================
# ORIENTATION AND SORTING OPTIONS
# ===============================================

get_sorting_options <- function() {
  list(
    list(sort = FALSE, sort_name = "Original_Order"),
    list(sort = TRUE, sort_name = "Sorted_by_Expression")
  )
}

get_orientation_options <- function(gene_group = NULL) {
  # SmelDMP gene groups: organs-as-rows layout only
  if (!is.null(gene_group) && grepl("SmelDMP", gene_group, ignore.case = TRUE)) {
    return(list(
      list(transpose = TRUE, orient_name = "Organs_as_Rows")
    ))
  }
  list(
    list(transpose = FALSE, orient_name = "Genes_as_Rows"),
    list(transpose = TRUE, orient_name = "Organs_as_Rows")
  )
}
